### PR TITLE
Add includes for open

### PR DESCRIPTION
**Pull request by JoelStienlet**
corrects my mistake, used string flags instead of int flags

### CODE REVIEW

**Comment by JoelStienlet** [comment]
@KjellKod  weird, I'm still seeing only appveyor, NOT travis! Is my github account cursed 😅 ?

**Comment by JoelStienlet** [comment]
@KjellKod if this one has still a problem I install ubuntu in a virtual machine, and do a final clean PR when every compilation/runtime problem is cleaned up on Ubuntu. I don't want you to waste time with this.

**Comment by JoelStienlet** [comment]
this is what I see right now: no travis 
Screenshot from 2020-04-10 17-06-04

**Comment by KjellKod** [comment]
Hmm. Maybe this explains it: https://docs.travis-ci.com/user/pull-requests/
Possibly it's because the PR is being pushed from a forked repo and the PR is not being pushed straight to the origin repo?

**Comment by KjellKod** [comment]
With this change the compilation issue is taken care of but it doesn't work. I've also checked this locally and it also fails with the same error 
```
Emulating memfd_create() in /Users/kjellhedstrom/ws/g3sinks/snippets/test_FileLog.cpp
ERROR: unable to unlink memfile_1 : No such file or directory
```

**Comment by KjellKod** [comment]
@JoelStienlet : another reason for Travis-CI to not show up is if the branch it not up to date with the latest from master. Please make sure to pull in the latest changes.

**Comment by JoelStienlet** [comment]
@KjellKod I've pulled master before issuing a completely new PR yesterday.

**Comment by KjellKod** [comment]
Got it. Please see the error above that I posted. Not a compilation error, a runtime error

**Comment by JoelStienlet** [comment]
@KjellKod  I suspect it is a missing O_CREAT flag, so the full flags parameter should be: O_RDWR | O_CREAT
I'm downloading ubuntu 18.04.4, I hope this triggers the same errors as travis. I'll check this both on my fedora and ubuntu, before I PR anything now.

**Comment by KjellKod** [comment]
I've verified it locally and it worked fine with the changes you proposed. Buidling it on Travis/OSX/Linux now. https://travis-ci.com/github/KjellKod/g3sinks/builds/159812154

**Comment by JoelStienlet** [comment]
@KjellKod good news! Thank you !

**Comment by KjellKod** [comment]
https://travis-ci.com/github/KjellKod/g3sinks/builds/159812154 worked like a charm. Still a freakin mystery why your PRs don't trigger Travis.

**Pull request merged**
