### PR TITLE
Added g3log_tracelogging sink

### PR DESCRIPTION
**Pull request by jjhegedus**
Kjell,
I've created the first cut of g3log_tracelogging.  I don't have unit tests or CI yet as I'm not yet sure how to set them up but I was able to set up a simple example and I verified that it works as expected.  I'll be reading up on ctest, gtest and Windows CI over the next few days to get there but I wanted to submit this as it is now so you could give me any suggestions you have.  I am very open to making changes and would appreciate any guidance you can give me.

Jeff

### CODE REVIEW

**Comment by jjhegedus** [comment]
I just realized that the last two changes I made didn't get into this pull request.  I'm not sure it's possible to update the pull request.  Is the best thing for me to do to close the pull request and resubmit the correct pull request?

**Comment by KjellKod** [comment]
If you have committed your changes and pushed them to your repo, to the correct branch then they will show up on the PR (your branch towards master on /KjellKod/g3sinks)

**Comment by jjhegedus** [comment]
I just pushed them to my repo on the correct branch.  Sorry for my ignorance and thanks again for you help.

**Comment by jjhegedus** [comment]
As I continue to learn more about CMake, I think I'd like to improve this and submit a new pull request at a later date.

**Comment by KjellKod** [comment]
sounds good! thanks for thorough diligence!

**Pull request closed without merging**
