### PR TITLE
new snippet: filelog with open file descriptor

### PR DESCRIPTION
**Pull request by JoelStienlet**
As included in the readme markdown: A simple file logger snippet, with the specificity that it logs to an open file descriptor passed by the user. This may solve specific corner cases where only file descriptors are available. Ex: log to shared memory (fd returned by memfd_create()). Or when file opening may be tricky and you want to do it manually, for example in a [setuid process](http://www.cis.syr.edu/~wedu/Teaching/cis643/LectureNotes_New/Race_Condition.pdf).

### CODE REVIEW

**Comment by KjellKod** [comment]
Hmm. It seems that for some reason travis CI builds are no longer working.

**Comment by KjellKod** [comment]
No. Travis seems to be working but it doesn't show up on check list. 
https://travis-ci.org/github/KjellKod/g3sinks/builds/668885820?utm_medium=notification&utm_source=github_status

**Comment by KjellKod** [comment]
Doesn't seem to work on OS X or potentially also not on Linux as written today. https://github.com/KjellKod/g3sinks/issues/83

**Comment by KjellKod** [comment]
@JoelStienlet : master branch failing https://travis-ci.com/github/KjellKod/g3sinks/builds/159224723

**Comment by JoelStienlet** [comment]
@KjellKod  Sorry about that, I'll investigate this issue, and try to find a solution ASAP.

**Pull request merged**
